fds_nginx:
  image: nginx:1.15-alpine
  container_name: fds_nginx
  ports:
    - "8080:80"
  volumes:
    - .:/var/www/vhosts/fds
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
  links:
    - fds_php

fds_php:
  build: .
  dockerfile: setup/dev/docker/php.dockerfile
  container_name: fds_php
  hostname: php
  volumes:
    - .:/var/www/vhosts/fds
  links:
    - fds_mysql

fds_mysql:
  image: mysql:5.7
  container_name: fds_mysql
  hostname: mysql
  ports:
    - 3320:3306
  environment:
    MYSQL_ROOT_PASSWORD: pass
    MYSQL_DATABASE: fds_dev
  volumes:
    - ./setup/dev/docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

fds_build:
  build: .
  dockerfile: setup/dev/docker/build.dockerfile
  container_name: fds_build
  volumes:
    - .:/build