fds_nginx:
  image: nginx:1.15-alpine
  container_name: fds_nginx
  ports:
    - "8080:80"
  volumes:
    - .:/var/www/vhosts/fds
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
  links:
    - fds_php

fds_php:
  container_name: fds_php
  hostname: php
  image: php:7.2-fpm
  volumes:
    - .:/var/www/vhosts/fds